### ISSUE TITLE
Potential minor bug

### ISSUE THREAD

**Issue by tst2005** [BoHeck/Annotorio#1]
I just read the code and see a potential mistake
in https://github.com/BoHeck/Annotorio/blob/master/data.lua#L3
To hide all technologies, the value `v.hidden` should be set to `true` instead of `false`, no ?

```diff
 --Hiding all existing technologies
 for i, v in pairs(data.raw.technology) do
-  v.hidden = false
+  v.hidden = true
   v.enabled = false
 end
```

**Comment by BoHeck** [comment]
the prototype  Technology has the attribute 

visible_when_disabled
Type: Types/bool
Default: false 

so that hidden wont matter unless its enabled. I dont want to hide them in case some other mod reactivates them. This way its also easier to catch a mistake
